stages:
  - init
  - test

lint:
  stage: init
  script:
    - flake8
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 50 mmdet


build:
  stage: init
  script:
    - python setup.py check -m -s
    - python -m pip install -e .

mmdet-test:
  stage: test
  script:
    - python -m pytest tests --cov-report=html --cov=mmdet
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 30 days

kneron-test:
  stage: test
  script:
    - echo "[WIP] This job test kneron-related functions."
